# Generated by Django 5.0.7 on 2024-07-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_remove_novel_poster_novel_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/novels/default_avatar.png', upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='novels.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='characters/')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.character')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='novels.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='music/')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='novels.novel')),
            ],
        ),
    ]
