# Generated by Django 5.0.7 on 2024-07-20 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_novel_cover_image_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='background',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='character',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='season',
            name='created_at',
        ),
        migrations.AddField(
            model_name='character',
            name='side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.background'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.music'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(upload_to='novels/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='novels/characters/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.character'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='novels/music/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover_image',
            field=models.ImageField(upload_to='novels/covers/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
