# Generated by Django 5.0.7 on 2024-07-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_dialogue_options_remove_background_novel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={},
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='content',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='episode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='novels.episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogue',
            name='next_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='novels.dialogue'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background', to='novels.novel'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='center', max_length=10),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='novels.dialogue')),
                ('next_dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='novels.dialogue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
