# Generated by Django 5.0.7 on 2024-07-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_alter_dialogue_options_remove_dialogue_novel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background', to='novels.background'),
        ),
    ]
