# Generated by Django 5.0.7 on 2024-07-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_alter_dialogue_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='progress',
        ),
    ]
