# Generated by Django 5.0.7 on 2024-07-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_rename_series_userprogress_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='episode',
            new_name='series',
        ),
    ]
