# Generated by Django 5.0.7 on 2024-07-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_remove_userprogress_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='series',
            new_name='episode',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'episode')},
        ),
    ]
