# Generated by Django 5.0.7 on 2024-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_rename_series_userprogress_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
