# Generated by Django 5.0.7 on 2024-07-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_background_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='episode',
            new_name='current_episode',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_progress_dialogues', to='novels.dialogue'),
        ),
        migrations.AlterField(
            model_name='character',
            name='side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_dialogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_choices', to='novels.dialogue'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues', to='novels.background'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'current_episode', 'current_dialogue')},
        ),
    ]
