# Generated by Django 5.0.7 on 2024-07-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_rename_episode_userprogress_current_episode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='next_dialogue',
            new_name='previous_dialogue',
        ),
    ]
