# Generated by Django 5.0.7 on 2024-07-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_rename_next_dialogue_dialogue_previous_dialogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='novels.episode'),
        ),
    ]
