# Generated by Django 5.0.7 on 2024-07-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0017_alter_dialogue_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
