# Generated by Django 5.0.7 on 2024-07-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0018_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('user', 'current_episode', 'current_dialogue'), name='unique_user_progress'),
        ),
    ]
