# Generated by Django 5.0.7 on 2024-07-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0020_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
