# Generated by Django 5.0.7 on 2024-08-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0021_remove_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.RemoveField(
            model_name='character',
            name='side',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='dialogue',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='order',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='choices',
            field=models.ManyToManyField(blank=True, to='novels.choice'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_dialogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_choices', to='novels.dialogue'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
