# Generated by Django 5.0.7 on 2024-08-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0023_remove_dialogue_previous_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='novel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
            preserve_default=False,
        ),
    ]
