# Generated by Django 5.0.7 on 2024-08-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0026_userprogress_novel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='novel',
        ),
    ]
