# Generated by Django 5.0.7 on 2024-08-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0027_remove_userprogress_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
    ]
